name: "Lighthouse - Raport jakości"

on: [push]

jobs:
  lighthouse-report:
    runs-on: ubuntu-latest
    steps:
      - name: Pobranie kodu
        uses: actions/checkout@v4

      - name: Audit Lighthouse
        # Używamy pełnej nazwy oficjalnego repozytorium
        uses: treosh/lighthouse-ci-action@v12
        with:
          staticDistDir: './'
          urls: |
            http://localhost:8080/index.html
          uploadArtifacts: true
          temporaryPublicStorage: true
